name: Manual Workflow
on: 
  workflow_dispatch:
    inputs:
      aws_region:
        description: 'AWS Region'
        required: false
        default: 'us-east-1'

jobs:
  call-aws-test:
    uses: ./.github/workflows/run-tests.yml
    with:
      aws_region: ${{ github.event.inputs.aws_region }}
    secrets: inherit