name: run-tests
on: 
  workflow_dispatch:
    inputs:
      aws_region:
        description: 'AWS Region'
        required: false
        default: 'us-east-1'
  workflow_call:
    inputs:
      aws_region:
        description: 'AWS Region'
        required: false
        type: string
        default: 'us-east-1'

jobs:
  test-aws:
    runs-on: ubuntu-22.04
    timeout-minutes: 5
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: ${{ inputs.aws_region }}    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Run AWS tests
        run: ./tests/run-tests.sh
